# Generated by Django 5.2.5 on 2026-02-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0004_transaction_verified_by_initiator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('L', 'Lend'), ('B', 'Borrow')], help_text='The type of transaction (Lend or Borrow).', max_length=1),
        ),
    ]
