# Generated by Django 5.2.5 on 2026-02-10 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('type', models.CharField(choices=[('digital', 'Digital Wallet'), ('bank', 'Bank Account'), ('cash', 'Cash'), ('other', 'Other')], default='other', max_length=20)),
                ('icon', models.CharField(blank=True, help_text="Icon name or simple text icon like 'e'", max_length=50, null=True)),
                ('color', models.CharField(default='#27272A', help_text='Hex color code', max_length=20)),
                ('identifier', models.CharField(blank=True, help_text='Account number or ID', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='income.wallet'),
        ),
    ]
