# Generated by Django 5.2.5 on 2026-02-10 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('expense', '0006_expense_ai_fields_and_receipt_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.category'),
        ),
    ]
